export default [
  {
    id: 1,
    img: {
      src: "https://unsplash.com/photos/EQ_SLlV7Ufc",
      alt: "Sunrise reflecting on Mount Fuji over calm water",
    },
    title: "Mount Fuji",
    country: "Japan",
    googleMapsLink: "https://maps.app.goo.gl/yU7ctPbCUz2qEV9Y6",
    dates: "10 April, 2023 - 22 April, 2023",
    text: "My journey to Mount Fuji was a mix of spiritual awakening and natural wonder. The climb, though exhausting, was filled with kind strangers and scenic rest stops. I experienced the famous Japanese sunrise from the summit, and the view was nothing short of divine. I savored fresh sushi in nearby Fujiyoshida and attended a tea ceremony hosted by a local family. This trip reminded me of the power of perseverance and the beauty of simplicity in Japanese culture.",
  },
  {
    id: 2,
    img: {
      src: "https://images.unsplash.com/photo-1537840096884-5793d84f8d8c?auto=format&fit=crop&w=800&q=80",
      alt: "Santorini sunset",
    },
    title: "Santorini",
    country: "Greece",
    googleMapsLink: "https://maps.app.goo.gl/XV5YmYEt7eS2WJxy5",
    dates: "05 June, 2023 - 15 June, 2023",
    text: "Santorini’s cliffside charm took my breath away. From the whitewashed buildings to the deep blue Aegean Sea, every corner was picture-perfect. I stayed in a cozy villa in Oia and spent my days sipping local wine and enjoying long walks along the caldera. The sunsets were poetic, turning the sky into a canvas of pink, orange, and lavender. It was the kind of peace that stays with you long after you leave.",
  },
  {
    id: 3,
    img: {
      src: "https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=800&q=80",
      alt: "Geirangerfjord, Norway",
    },
    title: "Geirangerfjord",
    country: "Norway",
    googleMapsLink: "https://maps.app.goo.gl/fhkJuBhmFDv47tiB7",
    dates: "01 Oct, 2021 - 18 Nov, 2021",
    text: "Geirangerfjord offered a raw, untouched beauty I’ve rarely seen. Waterfalls gushed down the steep cliffs as I cruised through the icy waters. Hiking up to the Flydalsjuvet viewpoint gave me a panoramic scene that looked like a painting. I spent time with a local family in a wooden cabin, learning about their sustainable lifestyle. Norway’s natural landscapes stirred something deep inside me—a reminder of Earth’s majestic power.",
  },
  {
    id: 4,
    img: {
      src: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      alt: "Marrakech souk",
    },
    title: "Marrakech",
    country: "Morocco",
    googleMapsLink: "https://maps.app.goo.gl/YEc1evpHka8mksw58",
    dates: "20 February, 2023 - 02 March, 2023",
    text: "Marrakech was a sensory explosion. I wandered through spice-laden souks, haggled with vendors over rugs, and sipped mint tea on rooftops while the call to prayer echoed in the distance. I visited the Majorelle Garden and learned about the history of Yves Saint Laurent in Morocco. Nights in the desert under a blanket of stars gave me a deep sense of stillness and connection to something ancient.",
  },
  {
    id: 5,
    img: {
      src: "https://images.unsplash.com/photo-1496395031226-0f7c1c0c1b0c?auto=format&fit=crop&w=800&q=80",
      alt: "Statue of Liberty",
    },
    title: "New York City",
    country: "USA",
    googleMapsLink: "https://maps.app.goo.gl/6My2ujHT9wtrJKCE6",
    dates: "10 August, 2022 - 22 August, 2022",
    text: "New York was everything I imagined—fast, loud, alive. I saw a Broadway show, walked Central Park, and visited museums like the Met and MoMA. Street food vendors kept me fed with hot dogs and pretzels, and I experienced the city from both the Top of the Rock and the ferry to Staten Island. Despite the chaos, the city gave me creative energy I hadn’t felt in years.",
  },
  {
    id: 6,
    img: {
      src: "https://images.unsplash.com/photo-1526481280690-967f61f7c73a?auto=format&fit=crop&w=800&q=80",
      alt: "Cape Town Table Mountain",
    },
    title: "Cape Town",
    country: "South Africa",
    googleMapsLink: "https://maps.app.goo.gl/4YkjsZTnfdGLoYvL9",
    dates: "14 December, 2022 - 03 January, 2023",
    text: "Cape Town combined raw nature with vibrant city life. I hiked up Table Mountain and paraglided over Signal Hill. The views were unreal. I explored Robben Island and reflected on Nelson Mandela’s legacy, a sobering and inspiring experience. Evenings were filled with live jazz in cozy bars and braai (barbecue) with locals. It was a trip of both thrill and deep meaning.",
  },
  {
    id: 7,
    img: {
      src: "https://images.unsplash.com/photo-1584164273070-55c1baf109ee?auto=format&fit=crop&w=800&q=80",
      alt: "Petra, Jordan",
    },
    title: "Petra",
    country: "Jordan",
    googleMapsLink: "https://maps.app.goo.gl/Zb63xZcPxKjwGmNc8",
    dates: "18 May, 2023 - 26 May, 2023",
    text: "Petra was like stepping into another world. Walking through the Siq and seeing the Treasury reveal itself was pure magic. I learned about the Nabatean civilization and how they engineered such marvels in the desert. Sleeping in a Bedouin camp under the stars was humbling, and I found deep respect for the resilient people of Jordan. It was history brought to life in the most stunning way.",
  },
  {
    id: 8,
    img: {
      src: "https://images.unsplash.com/photo-1590490352870-39f4807edcfb?auto=format&fit=crop&w=800&q=80",
      alt: "Sydney Opera House",
    },
    title: "Sydney",
    country: "Australia",
    googleMapsLink: "https://maps.app.goo.gl/ghWBJqThSVqgQayJA",
    dates: "03 November, 2022 - 17 November, 2022",
    text: "Sydney gave me the perfect balance of urban adventure and coastal bliss. I watched a show at the Opera House and surfed my first wave at Bondi Beach. I took a day trip to the Blue Mountains and learned about Aboriginal rock art. Australians were warm and humorous, and the seafood was fresh beyond words. I left with sun-kissed skin and a head full of happy memories.",
  },
  {
    id: 9,
    img: {
      src: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=800&q=80",
      alt: "Paris Eiffel Tower",
    },
    title: "Paris",
    country: "France",
    googleMapsLink: "https://maps.app.goo.gl/j3m4MfQZycFnAzRm9",
    dates: "12 March, 2022 - 25 March, 2022",
    text: "Paris felt like a living poem. I sipped espresso in sidewalk cafés, admired masterpieces in the Louvre, and watched the Eiffel Tower sparkle at night. I took long walks along the Seine, bought books from vintage sellers, and had the best croissants of my life in a tiny Montmartre bakery. Paris stirred my love for art, romance, and beauty in the everyday.",
  },
  {
    id: 10,
    img: {
      src: "https://images.unsplash.com/photo-1589758438368-06c4dc62a22f?auto=format&fit=crop&w=800&q=80",
      alt: "Rio de Janeiro beach",
    },
    title: "Rio de Janeiro",
    country: "Brazil",
    googleMapsLink: "https://maps.app.goo.gl/QaBguU7A5XtPV78G8",
    dates: "07 February, 2023 - 17 February, 2023",
    text: "Rio was all rhythm and color. I danced during Carnival, watched capoeira by the beach, and rode the cable car to Sugarloaf Mountain. Christ the Redeemer loomed over the city with open arms, and I felt welcomed by the energy of its people. The food, the samba, the street art—everything pulsed with life. It was a celebration of culture, freedom, and joy.",
  },
];
